[package]
name = "pe437xx"
version = "0.1.0"
edition = "2021"
authors = ["Ian McLinden <mclinden.ian@gmail.com>"]
description = "Drivers for the PE437xx family RF Digital Step Attenuators by Peregrine Semiconductor.\nCompatible with the PE43701, PE43702, PE43703, PE43704, PE43705, PE43711, PE43712, and PE43713."
readme = "README.md"
keywords = ["pe437xx", "dsa", "embedded-hal-driver", "rf"]
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/ianmclinden/pe437xx"
documentation = "https://docs.rs/pe437xx"
license = "MIT OR Apache-2.0"

[features]
default = []
# Enable async SPI support
async = ["dep:embedded-hal-async"]
# Enable defmt logging
defmt = ["dep:defmt"]
# Enable serde serialize+deserialize for crate types
serde = ["dep:serde"]
# Enable unchecked creation of crate types
unchecked = []

[dependencies]
defmt = { version = "1.1.1", optional = true }
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0.0", optional = true }
serde = { version = "1.0.229", default-features = false, features = [
    "derive",
], optional = true }
thiserror = { version = "2.0.20", default-features = false }

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", default-features = false, features = [
    "eh1",
    "embedded-hal-async",
] }
paste = "1.0"
tokio = { version = "1.53", features = ["macros", "rt"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }

[profile.release]
lto = true
